baseURL = 'https://softwareconviction.com/'
languageCode = 'en-us'
title = 'Blog on software, infrastructure and its accompanying lifestyle'
theme = "ananke"
disqusShortname = 'softwareconviction-com'
enableRobotsTXT = true